name: coronalmodeleval  # environment name
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy
  - jupyter notebook
  - matplotlib
  - numpy
  - pathlib
  - pandas
  - pip
  - pymdown-extensions
  - python == 3.11.0
  - scipy
  - sunpy == 4.1.2
  - wget
  - pip:
    - pfsspy
    - ipykernel
    - astrospice==0.2.0
    - heliopy
    - streamtracer
    - astrospice
    - pyspedas
